import Foundation

enum RemoteKey: String, Codable, CaseIterable, Sendable {
    case KEY_POWER, KEY_POWEROFF, KEY_POWERON, KEY_SLEEP, KEY_WAKEUP
    case KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT, KEY_ENTER, KEY_RETURN, KEY_EXIT
    case KEY_VOLUP, KEY_VOLDOWN, KEY_MUTE
    case KEY_CHUP, KEY_CHDOWN, KEY_CH_LIST, KEY_PRECH
    case KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_TTX_MIX
    case KEY_PLAY, KEY_PAUSE, KEY_STOP, KEY_FF, KEY_REWIND, KEY_REC, KEY_PLAYBACK
    case KEY_MENU, KEY_GUIDE, KEY_TOOLS, KEY_INFO, KEY_SOURCE
    case KEY_RED, KEY_GREEN, KEY_YELLOW, KEY_BLUE
    case KEY_CONTENTS, KEY_SMARTHUB, KEY_HOME, KEY_APP_SELECT
    case KEY_DTV, KEY_HDMI, KEY_HDMI1, KEY_HDMI2, KEY_HDMI3, KEY_HDMI4
    case KEY_AV1, KEY_AV2, KEY_COMPONENT1
    case KEY_ASPECT, KEY_PICTURE_SIZE, KEY_CAPTION, KEY_SUBTITLE
    case KEY_PANNEL_CHDOWN, KEY_EXT18
}
